<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        async function asyncFunction() {
            try {
                const result1 = await asyncOperation1();
                const result2 = await asyncOperation2(result1);
                const result3 = await asyncOperation3(result2);
                console.log(result1);
                console.log(result2);
                console.log(result3);

                return result3;
            } catch (error) {
                console.error(error);
                throw error;
            }
        }

        // Примеры асинхронных функций, которые возвращают промисы

        function asyncOperation1() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('Результат операции 1');
                }, 1000);
            });
        }

        function asyncOperation2(previousResult) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(`Результат операции 2, полученный из ${previousResult}`);
                }, 1000);
            });
        }

        function asyncOperation3(previousResult) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(`Результат операции 3, полученный из ${previousResult}`);
                }, 1000);
            });
        }

        // Вызов асинхронной функции и ожидание результата

        asyncFunction()
            .then((result) => {
                console.log(`Результат асинхронной функции: ${result}`);
            })
            .catch((error) => {
                console.error(`Ошибка в асинхронной функции: ${error}`);
            });
    </script>
</body>

</html>